INVALID_USERNAME_PWD="Incorrect username/password. Re-enter again."
USER_NOT_FOUND="Incorrect username/password"
UNEXPECTED_MSG_TYPE="Invalid message received."
INVALID_SIGNATURE="Signature verification failed"
SOCKET_TIMED_OUT="Socket timed out, try again later."
DUPLICATE_LOGIN="You are already logged in."
NON_REGISTERED_USER="You are not registered."
CHALLENGE_FAILED="User failed the challenge."
INCOMPLETE_SEND="Incomplete send request. Username and message required \n e.g send alice Hi Alice!."
INCORRECT_COMMAND="Command not correct"
REV_MSG_ERROR="Error occurred in UDP.py receive_message."
INVALID_ARGUMENT='Run as: python ChatClient.py -p <port-number>'
INVALID_HEARTBEAT='Invalid Hearbeat.'
INVALID_LOGOUT='Invalid logout request.'
INVALID_LIST_RQ='Invalid list request.'
NONCE_MISMATCH='Possible replay of packets. Nonce did not match'
INVALID_MSG_TYPE='Invalid message typr.'
DECRYPTION_ERROR='Error in decryption.'
QUIT_APP='Client logging out.'
INCORRECT_SEND_COMMAND='Incorrect send command e.g  send <username> <message>'

